# Generated by Django 5.1.4 on 2024-12-06 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineCourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=80)),
                ('courseDesc', models.TextField()),
                ('courseThumb', models.ImageField(upload_to='course')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineCourse.course_category')),
            ],
        ),
    ]
