# Generated by Django 5.1.4 on 2024-12-07 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineCourse', '0002_course_category_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineCourse.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineCourse.userdetails')),
            ],
        ),
    ]
