# Generated by Django 5.1.4 on 2024-12-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineCourse', '0004_userdetails_is_admin_alter_userdetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentlist',
            name='date',
            field=models.DateField(auto_now_add=True, default='2024-12-08'),
            preserve_default=False,
        ),
    ]
