# Generated by Django 5.1.4 on 2024-12-08 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineCourse', '0005_enrollmentlist_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollmentlist',
            old_name='date',
            new_name='enrollmentDate',
        ),
    ]
