# Generated by Django 5.1.4 on 2024-12-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineCourse', '0007_alter_enrollmentlist_enrollmentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentlist',
            name='enrollmentDate',
            field=models.DateField(),
        ),
    ]
