# Generated by Django 5.1.4 on 2024-12-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineCourse', '0008_alter_enrollmentlist_enrollmentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentlist',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
