# Generated by Django 5.1.4 on 2024-12-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineCourse', '0010_alter_enrollmentlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentlist',
            name='status',
            field=models.CharField(blank=True, default='true', max_length=5, null=True),
        ),
    ]
